[package]
name = "mksite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
pulldown-cmark = "0.9.1"
yaml-rust = "0.4.5"
